//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorevAtama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_GOREV
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public int ZORLUK { get; set; }
        public int PERSONELID { get; set; }
    
        public virtual TBL_PERSONEL TBL_PERSONEL { get; set; }
    }
}
